const EMAIL_REGEX = /^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+.[a-zA-Z0-9]+$/;
const EMAIL_ACTION = "EMAIL";
const USERNAME_ACTION = "USERNAME";
const PASSWORD_ACTION = "PASSWORD";
const CONFIRM_PASSWORD_ACTION = "CONFIRM_PASSWORD";
const FULL_NAME_ACTION = "FULL_NAME";

export {
  EMAIL_REGEX,
  EMAIL_ACTION,
  USERNAME_ACTION,
  PASSWORD_ACTION,
  CONFIRM_PASSWORD_ACTION,
  FULL_NAME_ACTION,
};
